### ISSUE TITLE
Null release IDs in response of /api/packages

### ISSUE THREAD

**Issue by garpu** [minetest/contentdb#129] opened 2019-03-05 20:21 UTC
Use the browse online content function, search for unternull.
Install unternull
start a game with it enabled.
Close unternull and exit minetest
Go back into browse online content, and an error is thrown.
Uninstall unternull mods, and it still throws an error.

Error message:

```
Loaded texture: /home/garpu/src/minetest/textures/base/pack/menu_header.png
Loaded texture: /home/garpu/src/minetest/games/minetest_game/screenshot.png
2019-03-05 15:12:35: ERROR[Main]: Main menu error: Runtime error from mod '' in callback handleMainMenuButtons(): ...rc/minetest/bin/../builtin/mainmenu/dlg_contentstore.lua:298: attempt to concatenate field 'release' (a nil value)
2019-03-05 15:12:35: ERROR[Main]: stack traceback:
2019-03-05 15:12:35: ERROR[Main]: 	...rc/minetest/bin/../builtin/mainmenu/dlg_contentstore.lua:298: in function 'load'
2019-03-05 15:12:35: ERROR[Main]: 	...rc/minetest/bin/../builtin/mainmenu/dlg_contentstore.lua:596: in function 'create_store_dlg'
2019-03-05 15:12:35: ERROR[Main]: 	...ard/src/minetest/bin/../builtin/mainmenu/tab_content.lua:158: in function 'handle_buttons'
2019-03-05 15:12:35: ERROR[Main]: 	/home/garpu/src/minetest/bin/../builtin/fstk/ui.lua:148: in function 'handle_buttons'
2019-03-05 15:12:35: ERROR[Main]: 	/home/garpu/src/minetest/bin/../builtin/fstk/ui.lua:192: in function </home/garpu/src/minetest/bin/../builtin/fstk/ui.lua:178>
```

**Comment by rubenwardy** [comment] 2019-03-05 21:14
Transferred this issue to the ContentDB backend

Today at 19:31:07 a release was made to Voxelgardens which added support for Minetest 5.0.0.

This bug was caused by a combination of:

1. the code checking whether a package supports a Minetest Version not checking whether the release is approved
2. the code returning the release number does check whether it is approved, and so returns null

**Comment by garpu** [comment] 2019-03-05 21:29
@Tmanyo where did you add the if statement, in the store.load() function?

**Comment by Tmanyo** [comment] 2019-03-05 21:46
@garpu I put it on line 296 and put the end on 300.

**Comment by rubenwardy** [comment] 2019-03-05 21:57
This should be fixed now, there's no need to change the if statement

**Comment by garpu** [comment] 2019-03-05 22:50
New git pull, or will there be an official bug release?

**Comment by rubenwardy** [comment] 2019-03-05 23:00
This isn't a bug in Minetest, it's a bug in ContentDB - the website the packages are found from

**Closed** 2019-03-13 14:37 UTC
