### ISSUE TITLE
[feature] adding maps next to games and mods

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [minetest/contentdb#372] opened 2022-03-06 21:20 UTC
so yes. now its possible only to make mods or games (!official wiki outdated!!!)

what if someone would make a map (normally like a user) from existing mods or on existing game (from existing ones in content db or default one). 
for the now only solution is to host a game. wouldnt it be good to make such game downloadable? cause if someone tries to upload contents of map as game throws errors (and its correct, yes)

ofcourse it'd need to mod minetest also (to add a tag in 'download online' section)

im interested mostly on sharing map.sqlite , map_meta.txt , world.mt and env_meta.txt

i heard already about [this mod](https://forum.minetest.net/viewtopic.php?f=9&t=24214) but its very slow so i thought to embed map installer to core of minetest and contentdb to just copy-paste content of a map to github and contentdb with would just copy if to menu of maps (not toggle for games).yes its fast and preserves all important data (just that we'd need to add mods folder for all mods + all important files like readme)

writing all the map node-by-node i think shouldnt be a requirement... (or very slowly generating map from some addons)

PS: copying world folder was tested by me and works (im opening this issue due to reasons [i want such thing btw ](https://github.com/hacknorris-aka-penguin/minetest-parkour-map);p)

**Comment by hacknorris-aka-penguin** [comment] 2022-03-06 21:31
something like this :

https://user-images.githubusercontent.com/97974194/156942971-8c6e28b5-d979-47d1-8ca0-c1b5d5d44070.mp4

=]

**Comment by rubenwardy** [comment] 2022-03-12 14:48
Thanks for the issue

This is a duplicate of #162

**Closed by rubenwardy** 2022-03-12 14:48 UTC
Labels: Feature
