### ISSUE TITLE
UX of home page show more button not good

### ISSUE THREAD

**Issue by MrRar** [minetest/contentdb#508] opened 2024-01-05 18:20 UTC
## Problem

On the CDB home page there is a show more button at the top of every top package category. I get confused if this button refers to the package collection above or below the button.

![CDB-prob](https://github.com/minetest/contentdb/assets/16406771/d3bb62d9-5096-40a7-90cb-c476b4e314ee)

## Solutions

One possible solution is to move the button closer to the collection it refers to and also closer to the title. Right now it's about half way between two collections.

![fixed-1](https://github.com/minetest/contentdb/assets/16406771/d2c31477-5f17-4228-8b03-44b2be667a30)

<br>
<br>

Another idea would be to replace the last item in the collection with the show more button. This seems very intuitive to me.

![fixed-2](https://github.com/minetest/contentdb/assets/16406771/faa89ae2-03dc-4aa5-b373-1878961faea1)

**Comment by rubenwardy** [comment] 2024-01-05 18:22
Hey, this is a duplicate of #297

**Closed by rubenwardy** 2024-01-05 18:22 UTC
Labels: Feature
