### ISSUE TITLE
VCS release creation fails for cgit repositories

### ISSUE THREAD

**Issue by orwell96** [minetest/contentdb#108] opened 2018-11-10 11:44 UTC
Task Failed

'\nfatal: unable to update url base from redirection:\n  asked for: http://:@git.bananach.space/advtrains.git/info/refs?service=git-upload-pack\n   redirect: https://git.bananach.space/cgit.cgi?url=advtrains.git/info/refs&service=git-upload-pack\n'

**Comment by rubenwardy** [comment] 2018-11-10 11:49
What URL did you give originally?

**Comment by orwell96** [comment] 2018-11-12 15:43
As VCS Repository is entered:
https://git.bananach.space/advtrains.git/

**Comment by sofar** [comment] 2018-11-14 05:42
Try finding out if you can use a git:// or git@ url instead. HTTPS can redirect, and this is likely the cause. It's potentially fixable, but, I'm not sure if @rubenwardy wants to do this, since there are security concerns about accepting redirects.

**Comment by orwell96** [comment] 2018-11-16 10:44
ok, I'll try this

**Comment by rubenwardy** [comment] 2019-08-31 21:14
```
rubenwardy:/tmp $ git clone git.bananach.space/advtrains.git
fatal: repository 'git.bananach.space/advtrains.git' does not exist
```

**Comment by rubenwardy** [comment] 2020-01-25 02:51
this should be fixed

**Closed by rubenwardy** 2020-01-25 02:51 UTC
Labels: + Releases, Unconfirmed Bug
