### ISSUE TITLE
Paging Breaks for New Content Beyond Initial Page on "See More" 

### ISSUE THREAD

**Issue by FriendlyGamer** [minetest/contentdb#208] opened 2020-06-16 14:46 UTC
## Summary
As mentioned on the titling you can see beyond the initial Page of the content, instead you must manually put in the page number you want. For instance to get page "2" you must tweak the link in the browser to the following "[https://content.minetest.net/packages/?page=2&sort=created_at&order=desc](https://content.minetest.net/packages/?page=2&sort=created_at&order=desc)". 
##### Steps to reproduce
Simply click "See More" then try picking a page number like "2" it will "reset" to the most popular sorting when it should be by release/updated date.

**Comment by rubenwardy** [comment] 2020-07-10 19:52
Duplicate of #205

**Closed by rubenwardy** 2020-07-10 19:52 UTC
Labels: Unconfirmed Bug
