### ISSUE TITLE
support filtering mods by supported game(s)

### ISSUE THREAD

**Issue by programmerjake** [minetest/contentdb#488] opened 2023-11-14 00:38 UTC
## Problem

I would like to be able to look through the mod list without having to manually filter out mods that are incompatible with the game I selected

## Solutions

Add a way for the mod list to be filterable by supported game(s)

## Alternatives

Do nothing...which makes contentdb very annoying to use when trying to find mods for the game I'm using.

**Comment by rubenwardy** [comment] 2023-11-14 01:08
This is the repository for the https://content.minetest.net/ website

On the ContentDB interface, this is already possible by going to the "hub" page of a game. For example: https://content.minetest.net/packages/Warr1024/nodecore/hub/

I suspect you meant to file this on the engine. In which case, this is a duplicate of #13851

**Closed by rubenwardy** 2023-11-14 01:08 UTC
Labels: Feature

**Comment by programmerjake** [comment] 2023-11-14 01:19
> On the ContentDB interface, this is already possible by going to the "hub" page of a game. For example: https://content.minetest.net/packages/Warr1024/nodecore/hub/

ah, I never noticed that button until now...
