### ISSUE TITLE
Add 'alpha/beta version' (or something like that) content flag

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#317] opened 2021-07-11 22:51 UTC
## Problem

Content DB is full of unfinished or half-finished and broken mods and games. That's not a problem in itself but ContentDB currently makes no distinction between unfinished and finished stuff.

This is bad because it makes it easy for players to be flooded with the unfinished stuff and be disappointed because nobody warned them.

## Solutions

Add a content flag to mark mods and games as being in an "alpha" or "beta" version, that is, in a state of development in which everything is still highly unstable, subject to heavy changes in future versions, full of critical bugs, etc. etc.

Maybe call this flag "unfinished" or some other generic term, not sure.

**Comment by Calinou** [comment] 2021-07-11 23:01
Maybe this could be done in a way similar to Blender's support level for add-ons: Official, Community and Testing.

The default is Community, and Testing can be chosen by add-on authors. By default, only Official and Community add-ons will appear in search results (Testing must be manually opted in by users).

**Comment by rubenwardy** [comment] 2021-07-24 16:41
duplicate of https://github.com/minetest/contentdb/issues/160

**Closed by rubenwardy** 2021-07-24 16:41 UTC
Labels: Feature
