### ISSUE TITLE
Add downloadable maps. 

### ISSUE THREAD

**Issue by Futuray-pgm** [minetest/contentdb#453] opened 2023-07-28 01:25 UTC
## Problem

I wanted to create maps and that the others players can try them. 

## Solutions

Add maps to contentdb, like it's already exist for mods, games and textures packs.
The only problem is that it must be supported by minetest engine too.

**Comment by rubenwardy** [comment] 2023-07-28 08:37
Duplicate of #162

**Closed by rubenwardy** 2023-07-28 08:37 UTC
