### ISSUE TITLE
Change the main thumbnail

### ISSUE THREAD

**Issue by runsy** [minetest/contentdb#225] opened 2020-07-20 14:17 UTC
## Problem

I want to change the main screenshot/thumbnail for my game. But I can not, because:

- I cannot replace it.
- The thumbnail is always the first one. I would have to delete all them and upload again.

## Solutions

- A checkbox to set a particular uploaded image as the thumbnail, as in Nexus Mods.

## Alternatives

- A replacement option.

**Comment by rubenwardy** [comment] 2020-09-16 22:42
Duplicate of #125

**Closed by rubenwardy** 2020-09-16 22:42 UTC
Labels: Feature
