### ISSUE TITLE
Allow mainain the "Provides" List as text input

### ISSUE THREAD

**Issue by bell07** [minetest/contentdb#153] opened 2019-06-03 15:06 UTC
The current way to maintain the "Provides" mods list is fine for small modpacks, but unuseable for big games:
![image](https://user-images.githubusercontent.com/4731334/58812209-a0b88200-8621-11e9-987b-e3dd90e5dab8.png)
Please add a simple way to update the mods list, maybe just using an edit field.

Or just auto-sort the list may helps to maintain the list..

**Comment by SmallJoker** [comment] 2019-06-03 18:12
Or use a item list where the indices are sorted, and multiple can be selected to remove.

**Comment by rubenwardy** [comment] 2019-07-01 23:59
duplicate of #114

**Closed by rubenwardy** 2019-07-01 23:59 UTC
